FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN rm requirements.txt

COPY ./insta_clone /app

CMD ["celery", "-A", "insta_clone.celery", "worker", "--loglevel=info"]